### ISSUE TITLE
Support for Laravel 10

### ISSUE THREAD

**Issue by dritanlatifi** [exodusanto/Laravel-Admin#47]
Hello,
is there an update is sight to support Laravel 10 and php 8.1?

Or is there an alternative, which has this support?

**Comment by exodusanto** [comment]
This package is a fork of an old package of Backpack creator. 
At the time, I took over this package because it was the only free option between Nova and Backpack. 
However, currently, after the release of Filament, I haven't maintained it anymore, considering the great community and features of Filament. Therefore, I recommend using Filament instead
